---

uiStyle:
  sprites:
    button.normal: { img: ui/ui_button.png, colour: "#9C5BB5" }
    button.down: { img: ui/ui_button.png, colour: "#913DA3" }
    button.hover: { img: ui/ui_button.png, colour: "#B68FCB" }
    
    input.box: { img: ui/ui_input.png, colour: "#9861B6" }

    list.background: ""
    list.item.normal: { img: ui/ui_list_item.png, colour: "#9C5BB5" }
    list.item.hover: { img: ui/ui_list_item.png, colour: "#B68FCB" }
    list.item.selected: { img: ui/ui_list_item.png, colour: "#913DA3" }

  borders:
    button.innerBorder: [ 5, 5, 5, 5 ]

    input.innerBorder: [ 6, 5, 6, 2 ]

    list.innerBorder: [ 0, 0, 0, 0 ]
    list.item.innerBorder: [ 6, 5, 6, 2 ]
    list.extraMouseBorder: [ 1, 1, 1, 1 ]

    tabs.innerBorder: [ 10, 0, 10, 0 ]
    tabs.item.innerBorder: [ 3, 1, 3, 1 ]
    tabs.extraMouseBorder: [ 0, 0, 0, 0 ]

    dropdown.innerBorder: [ 2, 1, 2, 2 ]

    dialogue.innerBorder: [ 3, 3, 4, 4 ]

    scrollbar.up.innerBorder: [ 3, 3, 3, 3 ]
    scrollbar.down.innerBorder: [ 3, 3, 3, 3 ]
    scrollbar.thumb.innerBorder: [ 3, 3, 3, 3 ]
    scrollDialogue.innerBorder: [ 6, 6, 6, 6 ]

    staticBox.innerBorder: [ 3, 3, 3, 3 ]

  audioClips:
    button.upSound: ""
    button.downSound: ""
    button.hoverSound: ""

    list.selectionChangedSound: ""

  textRenderers:
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    
    button.label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    
    input.label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    input.labelGhost: { font: Ubuntu Bold, size: 18, colour: "#7F7F7F" }

    list.label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFFCF" }
    list.selectedLabel: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }

  floats:
    list.gap: 1
    colourList.gap: 0
    tabs.gap: 1

...