---

widget:
  id: ""
  class: widget
  sizer:
    type: vertical
    children:
      - proportion: 0
        fill: centre
        widget:
          id: topLabel
          class: label
          text: "Enter the path of the project to load:"
      - proportion: 0
        fill: centre
        sizer:
          type: horizontal
          children:
            - proportion: 1
              widget:
                id: input
                class: textInput
                size: [400, 20]
            - proportion: 0
              widget:
                id: ok
                class: button
                text: "OK"

...